apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: dev-environment  # Match this with the service.yaml namespace
  labels:
    app: javaapp  # This label should match the selector in service.yaml
spec:
  replicas: 2  # Number of pods to deploy
  selector:
    matchLabels:
      app: javaapp  # This selector should match the label in the service.yaml
  template:
    metadata:
      labels:
        app: javaapp  # Ensure this label matches the service selector
    spec:
      containers:
      - name: javaapp
        image: namitha5/my-tomcat-app123:latest  # Replace with your actual Docker image
        ports:
        - containerPort: 8080  # This should match the targetPort in service.yaml
